apiVersion: v1
kind: Service
metadata:
  name: helloworld-wso2-service
  labels:
    app: helloworld-wso2-service
spec:
  type: LoadBalancer
  selector:
    app: helloworld-wso2-service  
  ports:
  - port: 8290
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-wso2-service
  labels:
    app: helloworld-wso2-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld-wso2-service
  template:
    metadata:
      labels:
        app: helloworld-wso2-service
    spec:
      containers:
      - name: helloworld-wso2-service
        image: dockrtraining/wso2-docker-demo:1.0.0-SNAPSHOT
        ports:
        - containerPort: 8290   
